-- =====================================================================
-- AI Digital Shadow for Software Developers
-- Supabase PostgreSQL Relational Schema
-- =====================================================================

-- Ensure schema public exists
CREATE SCHEMA IF NOT EXISTS public;

-- 1. Repositories
CREATE TABLE IF NOT EXISTS public.repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT UNIQUE,
    name TEXT NOT NULL,
    full_name TEXT NOT NULL UNIQUE,
    owner_login TEXT NOT NULL,
    html_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_repositories_full_name ON public.repositories(full_name);
CREATE INDEX IF NOT EXISTS idx_repositories_owner_login ON public.repositories(owner_login);


-- 2. Developers
CREATE TABLE IF NOT EXISTS public.developers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_login TEXT NOT NULL UNIQUE,
    name TEXT,
    email TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_developers_github_login ON public.developers(github_login);


-- 3. Commits
CREATE TABLE IF NOT EXISTS public.commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sha TEXT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES public.repositories(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES public.developers(id) ON DELETE SET NULL,
    message TEXT,
    committed_at TIMESTAMPTZ,
    html_url TEXT,
    CONSTRAINT uq_commits_repo_sha UNIQUE (repository_id, sha)
);

CREATE INDEX IF NOT EXISTS idx_commits_repository_id ON public.commits(repository_id);
CREATE INDEX IF NOT EXISTS idx_commits_developer_id ON public.commits(developer_id);
CREATE INDEX IF NOT EXISTS idx_commits_sha ON public.commits(sha);


-- 4. Pull Requests
CREATE TABLE IF NOT EXISTS public.pull_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_pr_number INT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES public.repositories(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES public.developers(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    body TEXT,
    state TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    merged_at TIMESTAMPTZ,
    merge_commit_sha TEXT,
    html_url TEXT,
    CONSTRAINT uq_pull_requests_repo_pr UNIQUE (repository_id, github_pr_number)
);

CREATE INDEX IF NOT EXISTS idx_pull_requests_repository_id ON public.pull_requests(repository_id);
CREATE INDEX IF NOT EXISTS idx_pull_requests_developer_id ON public.pull_requests(developer_id);
CREATE INDEX IF NOT EXISTS idx_pull_requests_number ON public.pull_requests(github_pr_number);


-- 5. Reviews
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_review_id BIGINT UNIQUE,
    pull_request_id BIGINT NOT NULL REFERENCES public.pull_requests(id) ON DELETE CASCADE,
    reviewer_id BIGINT REFERENCES public.developers(id) ON DELETE SET NULL,
    body TEXT,
    state TEXT,
    submitted_at TIMESTAMPTZ,
    commit_id TEXT,
    html_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_reviews_pull_request_id ON public.reviews(pull_request_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_id ON public.reviews(reviewer_id);


-- 6. Review Comments (Inline Diff Discussions)
CREATE TABLE IF NOT EXISTS public.review_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_comment_id BIGINT UNIQUE,
    pull_request_id BIGINT NOT NULL REFERENCES public.pull_requests(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES public.developers(id) ON DELETE SET NULL,
    body TEXT,
    path TEXT,
    line INT,
    diff_hunk TEXT,
    commit_sha TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    html_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_review_comments_pr_id ON public.review_comments(pull_request_id);
CREATE INDEX IF NOT EXISTS idx_review_comments_developer_id ON public.review_comments(developer_id);


-- 7. Issues (Excludes Pull Requests)
CREATE TABLE IF NOT EXISTS public.issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_issue_number INT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES public.repositories(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES public.developers(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    body TEXT,
    state TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    html_url TEXT,
    CONSTRAINT uq_issues_repo_issue UNIQUE (repository_id, github_issue_number)
);

CREATE INDEX IF NOT EXISTS idx_issues_repository_id ON public.issues(repository_id);
CREATE INDEX IF NOT EXISTS idx_issues_developer_id ON public.issues(developer_id);
CREATE INDEX IF NOT EXISTS idx_issues_number ON public.issues(github_issue_number);


-- 8. Issue Comments
CREATE TABLE IF NOT EXISTS public.issue_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_comment_id BIGINT UNIQUE,
    issue_id BIGINT NOT NULL REFERENCES public.issues(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES public.developers(id) ON DELETE SET NULL,
    body TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    html_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_issue_comments_issue_id ON public.issue_comments(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_comments_developer_id ON public.issue_comments(developer_id);


-- 9. Changed Files (Pull Request Level)
CREATE TABLE IF NOT EXISTS public.changed_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT NOT NULL REFERENCES public.pull_requests(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    status TEXT,
    additions INT DEFAULT 0,
    deletions INT DEFAULT 0,
    changes INT DEFAULT 0,
    sha TEXT,
    patch TEXT,
    blob_url TEXT,
    CONSTRAINT uq_changed_files_pr_filename UNIQUE (pull_request_id, filename)
);

CREATE INDEX IF NOT EXISTS idx_changed_files_pull_request_id ON public.changed_files(pull_request_id);


-- 10. Commit Files (Commit Level: Files changed by specific individual commits)
CREATE TABLE IF NOT EXISTS public.commit_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository TEXT NOT NULL,
    commit_sha TEXT NOT NULL,
    filename TEXT NOT NULL,
    status TEXT,
    additions INT DEFAULT 0,
    deletions INT DEFAULT 0,
    changes INT DEFAULT 0,
    patch TEXT,
    blob_url TEXT,
    raw_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_commit_files_repo_sha_filename UNIQUE (repository, commit_sha, filename)
);

CREATE INDEX IF NOT EXISTS idx_commit_files_repository ON public.commit_files(repository);
CREATE INDEX IF NOT EXISTS idx_commit_files_commit_sha ON public.commit_files(commit_sha);
CREATE INDEX IF NOT EXISTS idx_commit_files_repo_sha ON public.commit_files(repository, commit_sha);


-- =====================================================================
-- 11. Document Embeddings (pgvector Semantic Search)
-- =====================================================================

-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Table for storing semantic text embeddings (BAAI/bge-base-en-v1.5, 768 dimensions)
CREATE TABLE IF NOT EXISTS public.document_embeddings (
    id TEXT PRIMARY KEY,
    repository TEXT NOT NULL,
    document_type TEXT NOT NULL,
    source_id TEXT NOT NULL,
    developer TEXT,
    text TEXT NOT NULL,
    embedding VECTOR(768),
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for repository filtering and metadata queries
CREATE INDEX IF NOT EXISTS idx_document_embeddings_repository ON public.document_embeddings(repository);
CREATE INDEX IF NOT EXISTS idx_document_embeddings_doc_type ON public.document_embeddings(document_type);
CREATE INDEX IF NOT EXISTS idx_document_embeddings_source_id ON public.document_embeddings(source_id);

-- Cosine distance vector index (HNSW) for fast nearest neighbor search
CREATE INDEX IF NOT EXISTS idx_document_embeddings_embedding 
ON public.document_embeddings USING hnsw (embedding vector_cosine_ops);


-- =====================================================================
-- Semantic Similarity Search Function (PostgREST RPC)
-- =====================================================================
CREATE OR REPLACE FUNCTION public.match_documents (
    query_embedding VECTOR(768),
    match_count INT DEFAULT 5,
    filter_repository TEXT DEFAULT NULL
)
RETURNS TABLE (
    id TEXT,
    repository TEXT,
    document_type TEXT,
    source_id TEXT,
    developer TEXT,
    text TEXT,
    metadata JSONB,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        d.id,
        d.repository,
        d.document_type,
        d.source_id,
        d.developer,
        d.text,
        d.metadata,
        ROUND((1 - (d.embedding <=> query_embedding))::numeric, 4)::float AS similarity
    FROM public.document_embeddings d
    WHERE (filter_repository IS NULL OR d.repository = filter_repository)
    ORDER BY d.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;


-- =====================================================================
-- Permissions and Row-Level-Security (RLS) Configuration
-- Ensures Supabase PostgREST API can read/write to the tables
-- =====================================================================

-- Disable RLS on all tables so backend ingestion can insert smoothly
ALTER TABLE public.repositories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.developers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.commits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pull_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.issue_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.changed_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.commit_files DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_embeddings DISABLE ROW LEVEL SECURITY;

-- Grant access on public schema and all tables to standard roles
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.match_documents(VECTOR(384), INT, TEXT) TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;

-- =====================================================================
-- Reload PostgREST Schema Cache
-- CRUCIAL: Tells Supabase API layer to immediately index the new tables and RPC functions
-- =====================================================================
NOTIFY pgrst, 'reload schema';
