-- =====================================================================
-- AI Digital Shadow for Software Developers
-- Supabase PostgreSQL Relational Schema
-- =====================================================================

-- 1. Repositories
CREATE TABLE IF NOT EXISTS repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT UNIQUE,
    name TEXT NOT NULL,
    full_name TEXT NOT NULL UNIQUE,
    owner_login TEXT NOT NULL,
    html_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_repositories_full_name ON repositories(full_name);
CREATE INDEX IF NOT EXISTS idx_repositories_owner_login ON repositories(owner_login);


-- 2. Developers
CREATE TABLE IF NOT EXISTS developers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_login TEXT NOT NULL UNIQUE,
    name TEXT,
    email TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_developers_github_login ON developers(github_login);


-- 3. Commits
CREATE TABLE IF NOT EXISTS commits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sha TEXT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES developers(id) ON DELETE SET NULL,
    message TEXT,
    committed_at TIMESTAMPTZ,
    html_url TEXT,
    CONSTRAINT uq_commits_repo_sha UNIQUE (repository_id, sha)
);

CREATE INDEX IF NOT EXISTS idx_commits_repository_id ON commits(repository_id);
CREATE INDEX IF NOT EXISTS idx_commits_developer_id ON commits(developer_id);
CREATE INDEX IF NOT EXISTS idx_commits_sha ON commits(sha);


-- 4. Pull Requests
CREATE TABLE IF NOT EXISTS pull_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_pr_number INT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES developers(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    body TEXT,
    state TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    merged_at TIMESTAMPTZ,
    merge_commit_sha TEXT,
    html_url TEXT,
    CONSTRAINT uq_pull_requests_repo_pr UNIQUE (repository_id, github_pr_number)
);

CREATE INDEX IF NOT EXISTS idx_pull_requests_repository_id ON pull_requests(repository_id);
CREATE INDEX IF NOT EXISTS idx_pull_requests_developer_id ON pull_requests(developer_id);
CREATE INDEX IF NOT EXISTS idx_pull_requests_number ON pull_requests(github_pr_number);


-- 5. Reviews
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_review_id BIGINT UNIQUE,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(id) ON DELETE CASCADE,
    reviewer_id BIGINT REFERENCES developers(id) ON DELETE SET NULL,
    body TEXT,
    state TEXT,
    submitted_at TIMESTAMPTZ,
    commit_id TEXT,
    html_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_reviews_pull_request_id ON reviews(pull_request_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer_id ON reviews(reviewer_id);


-- 6. Review Comments (Inline Diff Discussions)
CREATE TABLE IF NOT EXISTS review_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_comment_id BIGINT UNIQUE,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES developers(id) ON DELETE SET NULL,
    body TEXT,
    path TEXT,
    line INT,
    diff_hunk TEXT,
    commit_sha TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    html_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_review_comments_pr_id ON review_comments(pull_request_id);
CREATE INDEX IF NOT EXISTS idx_review_comments_developer_id ON review_comments(developer_id);


-- 7. Issues (Excludes Pull Requests)
CREATE TABLE IF NOT EXISTS issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_issue_number INT NOT NULL,
    repository_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES developers(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    body TEXT,
    state TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    html_url TEXT,
    CONSTRAINT uq_issues_repo_issue UNIQUE (repository_id, github_issue_number)
);

CREATE INDEX IF NOT EXISTS idx_issues_repository_id ON issues(repository_id);
CREATE INDEX IF NOT EXISTS idx_issues_developer_id ON issues(developer_id);
CREATE INDEX IF NOT EXISTS idx_issues_number ON issues(github_issue_number);


-- 8. Issue Comments
CREATE TABLE IF NOT EXISTS issue_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_comment_id BIGINT UNIQUE,
    issue_id BIGINT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    developer_id BIGINT REFERENCES developers(id) ON DELETE SET NULL,
    body TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    html_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_issue_comments_issue_id ON issue_comments(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_comments_developer_id ON issue_comments(developer_id);


-- 9. Changed Files
CREATE TABLE IF NOT EXISTS changed_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_request_id BIGINT NOT NULL REFERENCES pull_requests(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    status TEXT,
    additions INT DEFAULT 0,
    deletions INT DEFAULT 0,
    changes INT DEFAULT 0,
    sha TEXT,
    patch TEXT,
    blob_url TEXT,
    CONSTRAINT uq_changed_files_pr_filename UNIQUE (pull_request_id, filename)
);

CREATE INDEX IF NOT EXISTS idx_changed_files_pull_request_id ON changed_files(pull_request_id);
